#!/bin/sh
echo "Please enter a English word for translation to Bengali:"
read word
 cap=`(grep -i -w -n $word /usr/trans/english | sed -n 's/^\([0-9]*\)[:].*/\1/p')`
bengali=`(grep -i -w $cap /usr/trans/bangla)`
bangla=${bengali##*|}
echo $bangla
echo "Press Enter to Exit"
read

